### ISSUE TITLE
Like Review

### ISSUE THREAD

**Issue by johnchakkour** [CSC207-2022F-UofT/course-project-npcs-ratemyuoft-project#5]
Implementation of the like 👍 and dislike 👎 features for reviews.

**Comment by Shawndavison26** [comment]
View the ViewCourse Usecase on Github to see what I did in regards to the Like-Review Usecase. I would recommend pulling from it so you can use the code i wrote and improve upon it.

<img width="1440" alt="Screen Shot 2022-12-03 at 4 33 06 PM" src="https://user-images.githubusercontent.com/100726103/205463118-8d37464c-b876-4182-8969-1eb9d9efaffe.png">

**Comment by KolyaLovesMarlboro** [comment]
done
